# Generated by Django 5.1.2 on 2024-10-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='parol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
