# Generated by Django 4.2.16 on 2024-11-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_parol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='admin',
            new_name='bugalter',
        ),
        migrations.AddField(
            model_name='users',
            name='it_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='omborchi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='prorektor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='xojalik_bolimi',
            field=models.BooleanField(default=False),
        ),
    ]
