# Generated by Django 4.2.16 on 2024-11-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='qr_code',
        ),
    ]
