# Generated by Django 4.2.16 on 2024-11-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userqrcode_qr_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqrcode',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='user_qrcode'),
        ),
    ]
