# Generated by Django 4.2.16 on 2024-12-06 08:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_userqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='users',
            name='bino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.binos'),
        ),
    ]
