# Generated by Django 4.2.16 on 2024-12-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_binos_users_bino'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='qr_code_link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
