# Generated by Django 4.2.16 on 2024-12-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_users_qr_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='qr_code_link',
            field=models.URLField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
