# Generated by Django 4.2.16 on 2024-12-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_users_qr_code_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='bugalter',
        ),
        migrations.RemoveField(
            model_name='users',
            name='it_park',
        ),
        migrations.RemoveField(
            model_name='users',
            name='komendant',
        ),
        migrations.RemoveField(
            model_name='users',
            name='omborchi',
        ),
        migrations.RemoveField(
            model_name='users',
            name='prorektor',
        ),
        migrations.RemoveField(
            model_name='users',
            name='superadmin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='xojalik_bolimi',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('prorektor', 'prorektor'), ('bugalter', 'bugalter'), ('xojalik', 'xojalik'), ('rttm', 'rttm'), ('omborchi', 'omborchi'), ('komendant', 'komendant')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
