# Generated by Django 4.2.16 on 2024-12-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_users_bugalter_remove_users_it_park_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='lavozim',
        ),
    ]
