# Generated by Django 4.2.16 on 2024-12-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_name_users_lavozim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='parol',
        ),
    ]
