# Generated by Django 4.2.16 on 2024-12-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_users_parol'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='parol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
