# Generated by Django 4.2.16 on 2024-12-27 09:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birlik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('buyurtma_role', models.CharField(choices=[('admin', 'admin'), ('prorektor', 'prorektor'), ('bugalter', 'bugalter'), ('xojalik', 'xojalik'), ('rttm', 'rttm'), ('omborchi', 'omborchi'), ('komendant', 'komendant')], max_length=30)),
                ('tasdiqlash', models.BooleanField(default=False)),
                ('rad_etish', models.BooleanField(default=False)),
                ('izoh', models.CharField(blank=True, max_length=355)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyurtmaMaxsulot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JamiMahsulot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.DecimalField(decimal_places=1, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Korzinka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KorzinkaMaxsulot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sorov', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('maxsulot_role', models.CharField(choices=[('xojalik', 'xojalik'), ('rttm', 'rttm')], default='xojalik', max_length=30)),
                ('maxviylik', models.BooleanField(default=False)),
                ('rasm', models.ImageField(null=True, upload_to='maxsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OlinganMaxsulotlar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OmborniYopish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('yopish', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talabnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talabnoma_pdf', models.FileField(blank=True, null=True, upload_to='talabnoma_pdf')),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='RadEtilganMaxsulotlar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.buyurtma')),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
