# Generated by Django 4.2.16 on 2025-01-20 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radetilganmaxsulot',
            name='rad_etgan_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ombor',
            name='maxsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot'),
        ),
        migrations.AddField(
            model_name='olinganmaxsulot',
            name='buyurtma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olingan_maxsulotlar', to='ombor.buyurtma'),
        ),
        migrations.AddField(
            model_name='olinganmaxsulot',
            name='maxsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot'),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='birlik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.birlik'),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='kategoriya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulot', to='ombor.kategoriya'),
        ),
        migrations.AddField(
            model_name='korzinkamaxsulot',
            name='korzinka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='ombor.korzinka'),
        ),
        migrations.AddField(
            model_name='korzinkamaxsulot',
            name='maxsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot'),
        ),
        migrations.AddField(
            model_name='korzinka',
            name='komendant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jamimahsulot',
            name='maxsulot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot'),
        ),
        migrations.AddField(
            model_name='buyurtmamaxsulot',
            name='buyurtma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='ombor.buyurtma'),
        ),
        migrations.AddField(
            model_name='buyurtmamaxsulot',
            name='maxsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='komendant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
