# Generated by Django 4.2.16 on 2025-01-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='kategoriya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulot', to='ombor.kategoriya'),
        ),
    ]
