# Generated by Django 5.1.2 on 2024-11-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0002_birlik_omborniyopish_alter_maxsulotnomi_kategoriya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzinka',
            name='tasdiqlash',
        ),
    ]
