# Generated by Django 4.2.16 on 2025-01-03 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ombor', '0003_alter_maxsulot_kategoriya'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OlinganMaxsulotlar',
            new_name='OlinganMaxsulot',
        ),
        migrations.RenameModel(
            old_name='RadEtilganMaxsulotlar',
            new_name='RadEtilganMaxsulot',
        ),
    ]
