# Generated by Django 5.1.2 on 2024-11-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0004_olinganmaxsulotlar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaxsulotNomi',
            new_name='Maxsulot',
        ),
    ]
