# Generated by Django 4.2.16 on 2025-01-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0004_rename_olinganmaxsulotlar_olinganmaxsulot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamimahsulot',
            name='maxsulot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot'),
        ),
        migrations.AlterField(
            model_name='korzinkamaxsulot',
            name='korzinka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korzinka', to='ombor.korzinka'),
        ),
    ]
