# Generated by Django 4.2.16 on 2025-01-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0005_alter_jamimahsulot_maxsulot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzinkamaxsulot',
            name='sorov',
        ),
    ]
