# Generated by Django 5.1.2 on 2024-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0005_rename_maxsulotnomi_maxsulot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korzinka',
            old_name='maxsulot_nomi',
            new_name='maxsulot',
        ),
        migrations.RenameField(
            model_name='olinganmaxsulotlar',
            old_name='maxsulot_nomi',
            new_name='maxsulot',
        ),
        migrations.RenameField(
            model_name='ombor',
            old_name='maxsulot_nomi',
            new_name='maxsulot',
        ),
        migrations.RemoveField(
            model_name='korzinka',
            name='kategoriya',
        ),
        migrations.RemoveField(
            model_name='olinganmaxsulotlar',
            name='kategoriya',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='kategoriya',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='maxviylik',
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='maxviylik',
            field=models.BooleanField(default=False),
        ),
    ]
