# Generated by Django 4.2.16 on 2025-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0006_remove_korzinkamaxsulot_sorov'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='sorov',
            field=models.BooleanField(default=False),
        ),
    ]
