# Generated by Django 4.2.16 on 2025-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0007_buyurtma_active_buyurtma_sorov'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='bugalter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='maxsulot_role',
            field=models.CharField(choices=[('xojalik', 'xojalik'), ('rttm', 'rttm')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='omborchi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='prorektor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='rttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='xojalik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='korzinka',
            name='maxsulot_role',
            field=models.CharField(choices=[('xojalik', 'xojalik'), ('rttm', 'rttm')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
