# Generated by Django 5.1.3 on 2024-11-07 04:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0007_remove_korzinka_user_remove_olinganmaxsulotlar_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamiMahsulot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.CharField(max_length=255)),
                ('birlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.birlik')),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
