# Generated by Django 5.1.3 on 2024-11-07 07:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0008_jamimahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamimahsulot',
            name='qiymat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='korzinka',
            name='qiymat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='olinganmaxsulotlar',
            name='qiymat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='qiymat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
