# Generated by Django 4.2.16 on 2025-01-14 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ombor', '0008_buyurtma_bugalter_buyurtma_maxsulot_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korzinka',
            name='komendant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
