# Generated by Django 5.1.3 on 2024-11-19 05:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0009_alter_jamimahsulot_qiymat_alter_korzinka_qiymat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='rad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='sorov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='tasdiq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jamimahsulot',
            name='qiymat',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.00'), max_digits=10),
        ),
    ]
