# Generated by Django 4.2.16 on 2025-01-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0009_alter_korzinka_komendant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='sorov',
        ),
        migrations.RemoveField(
            model_name='olinganmaxsulot',
            name='maxsulot',
        ),
        migrations.RemoveField(
            model_name='olinganmaxsulot',
            name='qiymat',
        ),
        migrations.RemoveField(
            model_name='radetilganmaxsulot',
            name='maxsulot',
        ),
        migrations.RemoveField(
            model_name='radetilganmaxsulot',
            name='qiymat',
        ),
    ]
