# Generated by Django 4.2.16 on 2025-01-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0010_remove_buyurtma_sorov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korzinkamaxsulot',
            name='korzinka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='ombor.korzinka'),
        ),
    ]
