# Generated by Django 4.2.16 on 2024-11-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0010_buyurtma_rad_buyurtma_sorov_buyurtma_tasdiq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='bugalter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='it_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='prorektor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='xojalik_bolimi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='it_park',
            field=models.BooleanField(default=False),
        ),
    ]
