# Generated by Django 4.2.16 on 2025-01-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0011_alter_korzinkamaxsulot_korzinka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmamaxsulot',
            name='buyurtma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='ombor.buyurtma'),
        ),
    ]
