# Generated by Django 4.2.16 on 2025-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0012_alter_buyurtmamaxsulot_buyurtma'),
    ]

    operations = [
        migrations.AddField(
            model_name='olinganmaxsulot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='radetilganmaxsulot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
