# Generated by Django 4.2.16 on 2024-11-29 04:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0012_talabnoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadEtilganMaxsulotlar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qiymat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=False)),
                ('birlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.birlik')),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.buyurtma')),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.maxsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
