# Generated by Django 4.2.16 on 2024-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0013_radetilganmaxsulotlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='bugalter_izoh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='it_park_izoh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='prorektor_izoh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='xojalik_bolimi_izoh',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
