# Generated by Django 4.2.16 on 2025-01-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0014_olinganmaxsulot_maxsulot_olinganmaxsulot_qiymat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olinganmaxsulot',
            name='maxsulot',
        ),
        migrations.RemoveField(
            model_name='olinganmaxsulot',
            name='qiymat',
        ),
        migrations.AlterField(
            model_name='olinganmaxsulot',
            name='buyurtma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.buyurtma'),
        ),
    ]
