# Generated by Django 4.2.16 on 2024-12-03 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ombor', '0015_rename_rad_buyurtma_omborchi_remove_buyurtma_tasdiq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radetilganmaxsulotlar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
