# Generated by Django 4.2.16 on 2024-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0016_radetilganmaxsulotlar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabnoma',
            name='talabnoma_pdf',
            field=models.FileField(blank=True, null=True, upload_to='talabnoma_pdf'),
        ),
        migrations.AlterField(
            model_name='talabnoma',
            name='talabnoma_pdf_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
