# Generated by Django 4.2.16 on 2024-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0019_buyurtma_maxsulot_it_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='izoh',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
