# Generated by Django 4.2.16 on 2024-12-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0020_buyurtma_izoh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='izoh',
        ),
    ]
