# Generated by Django 4.2.17 on 2024-12-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0022_maxsulot_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='rad',
            field=models.BooleanField(default=False),
        ),
    ]
